import { Hono } from "hono";
import { cors } from "hono/cors";
import { HTTPException } from "hono/http-exception";
import { logger } from "hono/logger";

import xrpcRoutes from "./routes/xrpc";

const app = new Hono<{
  Bindings: Env;
}>();

app.use(cors()).use(logger());

app.get("/", (ctx) => ctx.json({ name: "pds" }));

app.get("/.well-known/atproto-did", async (ctx) => {
  const handle = new URL(ctx.req.url).hostname.toLowerCase();
  const pdsHostname = ctx.env.PDS_HOSTNAME.toLowerCase();
  if (!handle.endsWith(`.${pdsHostname}`)) {
    return ctx.notFound();
  }

  const did = await ctx.env.HANDLES.get(handle);
  if (!did) {
    return ctx.notFound();
  }

  return ctx.text(did);
});

app.route("/xrpc", xrpcRoutes);

// oxlint-disable-next-line promise/prefer-await-to-callbacks
app.onError((err, c) => {
  if (err instanceof HTTPException) {
    // Return the error response generated by HTTPException
    return err.getResponse();
  }

  // For any other unexpected errors, log and return a generic 500 response
  console.error(err);
  return c.text("Internal Server Error", 500);
});

export default app;

export { PdsDurableObject } from "./pds-do";
