import { WorkerEntrypoint } from "cloudflare:workers";
import { Hono } from "hono";
import { cors } from "hono/cors";
import { HTTPException } from "hono/http-exception";
import { logger } from "hono/logger";

import { createOAuthAccessToken } from "./auth/session";
import type { OAuthAccessTokenInput } from "./auth/session";
import { InviteCodeRepository } from "./repositories/invite-code";
import xrpcRoutes from "./routes/xrpc";

const app = new Hono<{
  Bindings: Env;
}>();

app.use(cors()).use(logger());

app.get("/", (ctx) => ctx.json({ name: "pds" }));

app.get("/.well-known/oauth-protected-resource", (ctx) => {
  ctx.header("Cache-Control", "public, max-age=300");
  return ctx.json({
    authorization_servers: [ctx.env.ACCOUNTS_ORIGIN],
    resource: ctx.env.PDS_ORIGIN,
  });
});

app.route("/xrpc", xrpcRoutes);

// oxlint-disable-next-line promise/prefer-await-to-callbacks
app.onError((err, c) => {
  console.error(err);

  if (err instanceof HTTPException) {
    // Return the error response generated by HTTPException
    return err.getResponse();
  }

  // For any other unexpected errors, log and return a generic 500 response
  return c.text("Internal Server Error", 500);
});

export default {
  fetch: app.fetch,
};

export class PdsControlPlane extends WorkerEntrypoint<Env> {
  override fetch(request: Request): Response | Promise<Response> {
    return app.fetch(request, this.env, this.ctx);
  }

  generateInviteCode(): Promise<string> {
    return new InviteCodeRepository(this.env.PDS_KV).create();
  }

  issueOAuthAccessToken(input: OAuthAccessTokenInput): Promise<string> {
    if (
      input.audience !== this.env.PDS_ORIGIN ||
      input.issuer !== this.env.ACCOUNTS_ORIGIN
    ) {
      throw new Error(
        "OAuth token issuer or audience does not match PDS configuration"
      );
    }
    return createOAuthAccessToken(input, this.env.PDS_JWT_SECRET);
  }
}

export { RepoDO } from "@minisphere/repo-do";
