import { sql } from "drizzle-orm";
import { Hono } from "hono";
import { cors } from "hono/cors";
import { HTTPException } from "hono/http-exception";
import { logger } from "hono/logger";

import { createDatabase } from "./db";
import type { Database } from "./db";
import routes from "./routes";

const app = new Hono<{
  Bindings: Env;
  Variables: {
    db: Database;
  };
}>();

app
  .use(cors())
  .use(logger())
  .use((ctx, next) => {
    const db = createDatabase(ctx.env.DB);
    ctx.set("db", db);
    return next();
  });

app.get("/", (ctx) => ctx.json({ name: "minisphere-directory" }));

app.get("/_health", async (ctx) => {
  try {
    await ctx.var.db.run(sql`SELECT 1`);
    return ctx.json({ status: "ok" });
  } catch (error) {
    console.error("failed health check", error);
    throw new HTTPException(503, {
      message: "service unavailable",
    });
  }
});

app.route("/", routes);

// oxlint-disable-next-line promise/prefer-await-to-callbacks
app.onError((err, c) => {
  if (err instanceof HTTPException) {
    // Return the error response generated by HTTPException
    return err.getResponse();
  }
  // For any other unexpected errors, log and return a generic 500 response
  console.error(err);
  return c.text("Internal Server Error", 500);
});

export default app;
