const reservedUsernamesByCategory = {
  RFC2142: [
    "abuse",
    "ftp",
    "hostmaster",
    "info",
    "marketing",
    "news",
    "noc",
    "postmaster",
    "sales",
    "security",
    "support",
    "usenet",
    "uucp",
    "webmaster",
    "www",
  ],
  "auth/operators": [
    "admin",
    "administrator",
    "auth",
    "authentication",
    "authorize",
    "callback",
    "login",
    "logout",
    "moderation",
    "moderator",
    "oauth",
    "oidc",
    "operator",
    "password",
    "recovery",
    "register",
    "root",
    "signin",
    "signout",
    "signup",
    "staff",
    "system",
    "verify",
  ],
  historical: [
    "did-account",
    "did-accounts",
    "managed-account",
    "managed-accounts",
  ],
  infrastructure: [
    "assets",
    "cdn",
    "dev",
    "files",
    "gateway",
    "images",
    "internal",
    "mail",
    "media",
    "metrics",
    "mx",
    "ns1",
    "ns2",
    "origin",
    "proxy",
    "smtp",
    "staging",
    "static",
    "test",
    "uploads",
    "vpn",
  ],
  protocol: [
    "appview",
    "atproto",
    "bluesky",
    "bsky",
    "did",
    "entryway",
    "handle",
    "labeler",
    "minisphere",
    "pds",
    "plc",
    "relay",
    "repo",
    "xrpc",
  ],
  services: [
    "account",
    "accounts",
    "api",
    "configuration",
    "control",
    "control-plane",
    "dashboard",
    "directory",
    "handle-registry",
    "health",
    "healthz",
    "onboarding",
    "ready",
    "readyz",
    "status",
    "town",
    "well-known",
  ],
} as const;

const reservedUsernames = new Set<string>(
  Object.values(reservedUsernamesByCategory).flat()
);

export const isReservedUsername = (username: string) =>
  reservedUsernames.has(username.trim().toLowerCase());
