/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedAuthorizeRouteImport } from './routes/_protected/authorize'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedOnboardingUsernameRouteImport } from './routes/_protected/onboarding/username'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAuthorizeRoute = ProtectedAuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOnboardingUsernameRoute =
  ProtectedOnboardingUsernameRouteImport.update({
    id: '/onboarding/username',
    path: '/onboarding/username',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/authorize': typeof ProtectedAuthorizeRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/onboarding/username': typeof ProtectedOnboardingUsernameRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/authorize': typeof ProtectedAuthorizeRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/onboarding/username': typeof ProtectedOnboardingUsernameRoute
  '/settings': typeof ProtectedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/authorize': typeof ProtectedAuthorizeRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/onboarding/username': typeof ProtectedOnboardingUsernameRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/authorize'
    | '/dashboard'
    | '/onboarding/username'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/authorize'
    | '/dashboard'
    | '/onboarding/username'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/authorize'
    | '/_protected/dashboard'
    | '/_protected/onboarding/username'
    | '/_protected/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/authorize': {
      id: '/_protected/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof ProtectedAuthorizeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/onboarding/username': {
      id: '/_protected/onboarding/username'
      path: '/onboarding/username'
      fullPath: '/onboarding/username'
      preLoaderRoute: typeof ProtectedOnboardingUsernameRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAuthorizeRoute: typeof ProtectedAuthorizeRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedOnboardingUsernameRoute: typeof ProtectedOnboardingUsernameRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAuthorizeRoute: ProtectedAuthorizeRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedOnboardingUsernameRoute: ProtectedOnboardingUsernameRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
